import { Document, Page, StyleSheet, Text, View, renderToBuffer } from "@react-pdf/renderer";
import { formatMoney } from "@/lib/money";
import type { Report } from "@/lib/reports";

const s = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica", color: "#16211d" },
  title: { fontSize: 18, fontFamily: "Helvetica-Bold", color: "#0f5c4a" },
  subtitle: { marginTop: 2, marginBottom: 18, color: "#5d6b65" },
  heading: { marginTop: 14, marginBottom: 4, fontSize: 12, fontFamily: "Helvetica-Bold" },
  row: { flexDirection: "row", paddingVertical: 3, borderBottomWidth: 0.5, borderBottomColor: "#e4e2da" },
  head: { flexDirection: "row", paddingVertical: 3, borderBottomWidth: 1, borderBottomColor: "#16211d", fontFamily: "Helvetica-Bold" },
  total: { flexDirection: "row", paddingVertical: 4, fontFamily: "Helvetica-Bold" },
  footer: { position: "absolute", bottom: 24, left: 40, right: 40, fontSize: 8, color: "#5d6b65", textAlign: "center" },
});

export async function reportToPdf(report: Report, orgName: string): Promise<Buffer> {
  const cell = (i: number, n: number, amount: boolean) => ({
    flex: i === 0 ? 2 : 1,
    textAlign: amount ? ("right" as const) : ("left" as const),
    paddingRight: i === n - 1 ? 0 : 6,
  });
  const doc = (
    <Document title={`${report.title} — ${orgName}`} author="Ledgerline">
      <Page size="A4" style={s.page}>
        <Text style={s.title}>{orgName}</Text>
        <Text style={{ fontSize: 14, marginTop: 4 }}>{report.title}</Text>
        <Text style={s.subtitle}>{report.subtitle} · {report.currency}</Text>
        {report.sections.map((sec) => (
          <View key={sec.heading} wrap={false}>
            <Text style={s.heading}>{sec.heading}</Text>
            <View style={s.head}>
              {sec.columns.map((c, i) => (
                <Text key={i} style={cell(i, sec.columns.length, sec.amountCols.includes(i))}>{c}</Text>
              ))}
            </View>
            {[...sec.rows, ...(sec.totalRow ? [sec.totalRow] : [])].map((r, ri) => {
              const isTotal = !!sec.totalRow && ri === sec.rows.length;
              return (
                <View key={ri} style={isTotal ? s.total : s.row}>
                  {r.map((c, i) => {
                    const amount = sec.amountCols.includes(i);
                    return (
                      <Text key={i} style={cell(i, r.length, amount)}>
                        {amount && c !== "" ? formatMoney(c, report.currency) : c}
                      </Text>
                    );
                  })}
                </View>
              );
            })}
          </View>
        ))}
        <Text style={s.footer} fixed render={({ pageNumber, totalPages }) => `Generated by Ledgerline · page ${pageNumber} of ${totalPages}`} />
      </Page>
    </Document>
  );
  return renderToBuffer(doc);
}
